### ISSUE TITLE
Branch probabilities

### ISSUE THREAD

**Issue by qwertie** [WebAssembly/branch-hinting#14]
Have you considered supporting an estimated probability for the hint?

I am thinking that an optimizer could make better decisions if it had a probability, e.g. it could be that a certain optimization is only worthwhile if branch taken is at least 3x more likely than branch-not-taken, and would actually slow down the code if branch-taken is only 2x more likely.

To minimize hint sizes (and thus file sizes), perhaps a logarithmic likelihood would be best, e.g. using a formula such as (2^(x/4)):

- 0 => branches are equally likely (or, alternately, indicates unknown probability)
- 1 => 119% as likely
- 2 => 141% as likely
- 3 => 168% as likely
- 4 => 200% as likely
- 5 => 238% as likely
- 6 => 282% as likely
- 7 => 336% as likely
- 8 => 400% as likely
- 12 => 800% as likely
- 30 => 181 times as likely

As an example of how to implement this, the probability could be added as high bits on the existing 1-bit hint: bit 0 = branch likely taken, bits 1-5 = probability.

**Comment by yuri91** [comment]
It was considered, but ultimately I don't think it makes sense:

Tracking branch probabilities is useful in general, but it is a thing that is best done in the compiler. When the compiler emits the final wasm code, it already used this data to inform the codegen.

The wasm code is considered already optimized, and the main thing that remains,and that cannot be done by the compiler, is the layout of the final native assembly code.

Here the choice is to either treat the two destinations of the branch equally, or to treat one as very unlikely and put it at the end of the function code.

And this is why in V8, which has already the concept of branch hinting internally, the only options are "BranchNoHint", "BranchExpectFalse", "BranchExpectTrue".

So while it is possible that the probability information could be used in some circumstances, I think that engines would still just have a threshold  value and just use those 3 options.
