### ISSUE TITLE
CI failure on JS test

### ISSUE THREAD

**Issue by yuri91** [WebAssembly/branch-hinting#21]
See https://github.com/WebAssembly/branch-hinting/actions/runs/5423640455/jobs/9861859713

When running in the interpreter the tests for branch hinting run successfully, but when running in JS they fail.
The reason is that some tests expect a validation failure. The ability to fail on custom sections error was added to the interpreter, but it won't be added to browser engines.

The options as I see it are:
- Never run the JS version of custom section tests
- Consider valid that an expected validation error succeeds  when running custom sections tests 
- ?

This issue didn't come up in the Annotations repo because those tests only use assert_malformed and not assert_invalid.

@rossberg Do you have a suggestion on how to proceed? It should be relatively easy to add option 2, but maybe running the JS tests is just pointless for custom sections.

**Comment by rossberg** [comment]
Well, I don't think it's pointless for custom sections -- that would be saying the tests are mostly pointless, wouldn't it?

Perhaps we need distinguished assertions for custom sections, i.e., assert_malformed_custom and assert_invalid_custom? Then other clients of the test suite can implement them as they see fit.

**Comment by yuri91** [comment]
I mean specifically testing the JS engines, since vendors suggested that they are not interested in adding a "custom validation mode" to them. Testing in the interpreter (and any third party that opts in) would still be done.

Adding a different kind of assertion makes sense though.

**Comment by rossberg** [comment]
I'd expect that even JS engines might still desire to use the test suite to test their implementation, perhaps running it in a non-production mode or something.
