### ISSUE TITLE
Are "likely taken" offsets redundant?

### ISSUE THREAD

**Issue by jayphelps** [WebAssembly/branch-hinting#3]
0 | likely not taken
-- | --
1 | likely taken

The proposal is currently somewhat ambiguous around whether *every* branch should have a record for whether it is likely taken, or not likely taken.

Is the intent that every branch is considered one or the other, or whether there's a third implicit state where it's neither likely nor unlikely?

If there is no third state, would there be a benefit to omitting "likely" branch offsets since they can be implicitly assumed automatically? That is, the section would only need to record branches were are "likely not taken"? The benefit being saving of bytes.

**Comment by lars-t-hansen** [comment]
I would hope that tools only emit this when they have specific information about the branch, ie they're reflecting an annotation in the source code.  (Otherwise I'd start worrying a lot about bloat.)

**Comment by jayphelps** [comment]
Yeah, if that's the idea this lands on I think it'll be important to make that clear--that most branches in practice probably don't have any entry at all and that just because a branch is NOT "likely not taken" doesn't mean it's "likely taken". That's super confusing IMO though, and I'm still skeptical that there is a difference in practice from "likely taken" and the third "neither likely nor unlikely" taken when you can mark branches as "likely not taken".

But I'll keep an open mind since tools like LLVM go a step further and have a "weight" of how likely instead of just likely/unlikely/neither likely nor unlikely (as I'm sure many Wasm folks know)

**Comment by sunfishcode** [comment]
The third state is "I don't know", which is a very common case. It's important to give producers a way to say "I don't know", because if they arbitrarily pick "likely" or "likely not" when they don't actually know anything, consumers wouldn't be able to trust the hints even in cases where producers do know something.

**Comment by jayphelps** [comment]
Apologies, that's not what I was intending to suggest. I'll collect my thoughts and if I can find a better way to express my question I'll circle back. Thanks!
