### ISSUE TITLE
Other types of hints / syntax tweak

### ISSUE THREAD

**Issue by lars-t-hansen** [WebAssembly/branch-hinting#6]
Is it worth the bother to consider that we may want other types of per-bytecode hints in the future and that we should add a little generality to allow for that and avoid adding one section per hint class in the future?  The new Motivation document brings up PGO as a source of branch hints.  But PGO might also provide other information, such as likely trip counts for loops (could be used to drive unrolling or tiling?)  Consider a `kind` byte prefixing each bytecode offset in each function section, the syntax for a hint would then be `kind` `offset` `payload` where `payload` may vary with `kind`.

For compression, the `kind` could sometimes be combined with the `payload`; for branch hints, we'd have kind=0 for not-taken branch and kind=1 for taken branch.

Viewed a little differently, then, I'm proposing that we change the syntax of the hinting section to put the branch hint before the bytecode index, allowing us the extension outlined above in the future at zero cost to us now.

**Comment by lars-t-hansen** [comment]
Taking that one step further, the proposal could easily allow for function-level hints (hotness of the function for example) by including a single zero byte at the start of each function section, which would be a count of function-level hints following, before the bytecode hints.  For the time being, we need define no such hints.

And then perhaps the section should be called "performanceHints" and not "branchHints".

**Comment by yuri91** [comment]
Leaving room for future expansions and forward compatibility of the format is surely valuable.

Merging the `kind` with the `payload` seems reasonable, but I am not sure what difference it makes if the `offset` comes first or second.
We could just say that both `payload` and `offset` are `u32` uleb encoded. 
In the current situation with only 0 and 1 as possible payloads, they will still be 1 byte long.

Leaving space for function hints seems also fine, as long as we don't inflate this proposal with their specification (and as you said, we can avoid it).

**Comment by lars-t-hansen** [comment]
By placing the kind first, we leave things open for future encodings where there might not be a simple bytecode offset.  The cost is zero, and it creates flexibility.  (I agree the kind could also be a leb.)

For example, if a future hint type becomes prevalent it would be more compact to encode the "offset" as a delta from the previous hint's offset within the same function; the kind would communicate the encoding.

**Comment by yuri91** [comment]
I opened a PR with the modifications (except for renaming the  section, which I believe should be a separate issue).

I will keep it open for a bit for potential feedback.

**Comment by yuri91** [comment]
I merged the PR. It should address this issue (minus the renaming of the section, tracked in https://github.com/WebAssembly/branch-hinting/issues/7).

Feel free to reopen if you think that something is missing
