### ISSUE TITLE
Change section name?

### ISSUE THREAD

**Issue by yuri91** [WebAssembly/branch-hinting#7]
I am splitting this issue from https://github.com/WebAssembly/branch-hinting/issues/6

If we are going to make the section more flexible and allow different types of hints in the future, it makes sense to rename the section from "branchHints" to something else.

"performanceHints" seems like a good candidate.

**Comment by rossberg** [comment]
As a stylistic remark, I would also suggest to spell it `performance-hints` or `performance_hints` (or maybe `compilation-hints`?), since camelCasing is not used anywhere else in Wasm.

**Comment by yuri91** [comment]
The camel case originated from the "compilationHints" custom section used in V8 (from which I took inspiration).

I would avoid `compilation-hints` because of the possible confusion with the above, but `performance-hints` seems good.

**Comment by rossberg** [comment]
As a general remark, an individual engine making the questionable choice to clobber a good generic name should not be a deciding factor. ;)  I would suggest that V8 uses a suitable prefix like `v8-compilationHints` for proprietary custom sections.

**Comment by yuri91** [comment]
Well, I don't disagree.

`compilation-hints` could also be a more general name, since there may be future hints that are not strictly related to performance.

Maybe the general issue of prefixing non-standard section names should be discussed in the CG.

**Comment by yuri91** [comment]
Thinking about it, even "compilation" is potentially misleading.

maybe `function-hints`, `code-hints` or even just `hint` (considering that the name section is just called `name`) is better.

**Comment by yuri91** [comment]
I am closing this since the proposal changed in the meantime and there is already a new name: `code_annotation.branch_hint`.

That name also has problems, but related to the `custom_annotation` part (see https://github.com/WebAssembly/tool-conventions/issues/179), so the corresponding issue is in the tool-convetions repo.
